# print('some code')# try:##     print(len(21))#     print(my_variable)#     print(len(21))# except NameError:#     print("Name error occurs")# except TypeError:#     print('TypeError')# print('code_after_error')user_dict = {'First_Name': 'Alex', 'LastName': 'Clare', 'Age': '22'}# print(user_dict['LastName'])## print(user_dict['Name'])# print(user_dict.get('Nme'))def get_dict_values(dictionary, key):    '''    :param dictionary:    :param key:    :return:    None when incorrect key    '''    try:        return dictionary[key]    except KeyError:        return Nonet=get_dict_values(user_dict,'First_e')print(t)